spring:
  datasource:
    username: ${USERNAME}
    password: ${PASSWORD}
    url:  ${URL}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      format_sql: true
      dialect: ${DIALECT}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: "okorojeremiah91@gmail.com"
    password: "fuks rgon vyvw nnzy"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


project:
  poster: poster/

base:
  url: ${BASE_URL}
