spring:
  datasource:
    username: ${USERNAME}
    password: ${PASSWORD}
    url:  ${URL}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      format_sql: true
      dialect: ${DIALECT}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

project:
  poster: poster/

base:
  url: ${BASE_URL}
