spring:
  datasource:
    username: root
    password: Slimjay91@
    url: jdbc:mysql://localhost:3308/movies
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect


project:
  poster: poster/

base:
  url: "http://localhost:8080"
